homepage: "https://github.com/vercel/workflow"
language: javascript
primary_contact: "ferminbaudino@gmail.com"
main_repo: "https://github.com/vercel/workflow.git"
sanitizers:
  - address
fuzzing_engines:
  - libfuzzer
